---
title: "CV"
format: html
---

## Raghav Bhatia

Raghav.bhatia@mail.utoronto.ca | (437) 424-9697 | https://www.linkedin.com/in/raghav-bhatia-731a351b4

### EDUCATION
Trinity College, University of Toronto St. George, Toronto, ON                                       [Sep. 2022 – present]

Honors Bachelor of Science (HBSc.), Mathematical Applications in Economics and Finance | Major: Statistics | Major: Economics

Cumulative GPA: 3.85/4.00 | Anticipated Graduation: April 2025

• Notable Awards: Dean’s List Scholar, 2022 – present; International Scholar Award, 2022-2026 

• Relevant Coursework: Macroeconomic and Microeconomic Theory, Non-linear Optimization, Probability Theory, Methods of Data Analysis, Partial Differential Equations and Real Analysis

### WORK EXPERIENCE
Nimai Management Consultants                                        Dec. 2020

Interned as a Mergers and Acquisitions Analyst                                                        [Dubai, United Arab Emirates]

• Created a Discounted Cash Flow and Leverage Buyout Model for valuing companies and generating optimal debt strategies to maximize the acquisitions’ return at exit. Used the company’s balance sheet and cash flow statement to project future cash flow required to pay back the debt incurred from the leverage buyout and thereby project a return schedule for an exit in the future.

• Compiled Merger and Acquisition data for FMCG companies in the Middle East and Africa to extrapolate revenue and profitability multiples in the sector.

### PROJECTS
#### Dynamic Hedging and Mortgage-Backed Securities (MBS) Models            [Mar. 2021]

• Constructed Dynamic Hedging Portfolios to replicate European Option payoffs using a Delta-Gamma hedging framework. 

• Analyzed Mortgage Payment Data to simulate the payoffs of Principle Only and Interest Only Mortgage-Backed Securities. 

##### Creative Destruction as a Guide for Growth Policy - A Stable Equilibrium Policy Analysis for Reallocating R&D Investment across Firms         [Feb. 2024]

• Utilized a stable equilibrium model which captured the relationship between creative destruction and aggregate real growth. Focused on the reallocation of investments across firms as the main factor behind the creative destruction process. 

• Used the model setup to evaluate various fiscal policy measures aimed at reallocating investment capital across firms. Found the counter-intuitive recommendation of increasing taxes as boosting growth vis-à-vis increasing subsidies. 


### CORE COMPETENCIES
Macroeconomic Modelling | Mathematical Optimization and Analysis | Risk and Credit Analysis | Data Analysis | Quantitative Research

### TECHNOLOGIES
Python | Excel | SQL | R 

